### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by Batanin** [BigNerd95/RouterOS-Backup-Tools#10]
Hello, there is such a situation.
# ./ROSbackup.py decrypt -i MikroTik-encrypted.backup -o MikroTik-plaintext.backup -p password
** Decrypt Backup **
Traceback (most recent call last):
  File "./ROSbackup.py", line 426, in <module>
    main()
  File "./ROSbackup.py", line 415, in main
    decrypt(args.input, args.output, args.password)
  File "./ROSbackup.py", line 219, in decrypt
    magic, length = get_header(input_file)
  File "./ROSbackup.py", line 23, in get_header
    header = struct.unpack('<II', data)
struct.error: unpack requires a bytes object of length 8

**Comment by BigNerd95** [comment]
Can't help without having the encrypted back file you used

**Comment by Batanin** [comment]
[MikroTik.zip](https://github.com/BigNerd95/RouterOS-Backup-Tools/files/4275174/MikroTik.zip)

**Comment by Batanin** [comment]
???

**Comment by BigNerd95** [comment]
This is a plaintext backup
```
./ROSbackup.py info -i MikroTik.backup
** Backup Info **
RouterOS Plaintext Backup
Length: 91999 bytes
```

You dont have to decrypt it
Just extract

```
./ROSbackup.py unpack -i MikroTik.backup -d asd
** Unpack Backup **
RouterOS Plaintext Backup
Length: 91999 bytes
Extracting backup...
Wrote 102 files pair in: asd
```

**Comment by Batanin** [comment]
Hello, how can I open a. *dat file
I need to edit the password on admin.
Thanks for the previous answer !!!

**Comment by Batanin** [comment]
# ./ROSbackup.py bruteforce -i MikroTik-encrypted.backup -w wordlist.txt
** Bruteforce Backup Password **
RouterOS Encrypted Backup
Length: 92035 bytes
Salt (hex): f75ca7667705a3cb46dee1a4b403bc3a9c378d0d1a1afd474e6966493ef8ab82
Magic Check (hex): db620f14
Brute forcing...
Password NOT found

**Comment by Batanin** [comment]
And the password is definitely there

**Comment by Batanin** [comment]
???

**Comment by Batanin** [comment]
Thank you, I have already reset and reconfigured myself.
