### ISSUE TITLE
extract_user.py inactive

### ISSUE THREAD

**Issue by minhdanlc124** [BigNerd95/RouterOS-Backup-Tools#24]
i unpack the backup file and try to extract the user but nothing comes up i try `cat user.bat` with encoded characters and see user with encoded character
user.dat file content is it the user?
cat bb3/user.dat
�M2�
�              A�Mb
                  ��    �                       �!!1!   o���ƛz��sB��gx�NÉP��8� 1��7�*;>~�q  �Z!
                   nguyenvanduc!admin�M2�
�              Y�Yb                                                                           ��    �                       �!system default user!1!����/Y8L�!���^L�
            ,�n��� 1[�졖:��v�U�G?!admindmin

**Comment by lduczmal** [comment]
I also has problem with extracting users and after some investigation I've discovered that source of problem is  line  16 in file extract_user.py
`pass_data = entry.split(b"\x11\x00\x00\x21")[1]`
This line cause following error
```
Traceback (most recent call last):
  File ".\extract_user2.py", line 72, in <module>
    user_pass = get_pair(user_file)
  File ".\extract_user2.py", line 49, in get_pair
    pass_data = entry.split(b"\x11\x00\x00\x21")[1]
IndexError: list index out of range
```
I had to modify original python file a little bit to uncover the error. 
I don't know structure of user.dat file, information published in README.md attached to this repo is not clear for me, thus I can't repair  extract_user.py
Of course source of problem could be not in python script, but in user.dat file - maybe its structure is broken in some why?...
Best regards
LukiD
