### ISSUE TITLE
um4.dat file missing error

### ISSUE THREAD

**Issue by g3d12** [BigNerd95/RouterOS-Backup-Tools#25]
Hi
Can you please help me with resetting password process. I got unfortuanlety such an error:
Traceback (most recent call last):
  File "/home/kabs/Pobrane/mtkk/RouterOS-Backup-Tools/ROSbackup.py", line 595, in <module>
    main()
  File "/home/kabs/Pobrane/mtkk/RouterOS-Backup-Tools/ROSbackup.py", line 590, in main
    reset_password(args.input, args.default, args.output)
  File "/home/kabs/Pobrane/mtkk/RouterOS-Backup-Tools/ROSbackup.py", line 455, in reset_password
    shutil.copy(temp_dir+'/default/'+file, temp_dir+'/original/'+file)
  File "/usr/lib/python3.10/shutil.py", line 417, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './tempDir/default/um4.dat'

**Comment by kaulpa** [comment]
Hi there

I had the same issue and was able to solve it by a small modification of the script.
Because the um4.* files aren't available in my backups, I removed them form the overwrite_list at line 449. In my case it looks now this way.
"overwrite_list = ['user.dat','user.idx']"

So I was able to run the tool and reset my password.

**Comment by Wit4r7** [comment]
Thank you so much for this, :) Just saved me couple of hours to configure my router agin!
